language: java

matrix:
  include:
    - jdk: openjdk7
    - jdk: oraclejdk7
      dist: precise
    - jdk: oraclejdk8
    - jdk: oraclejdk9

script:
  - ./gradlew clean test

notifications:
  email:
    on_success: never

sudo: false
